(function() {var implementors = {};
implementors['tempfile'] = [];implementors['tempfile'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors['tempfile'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors['tempfile'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors['tempfile'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors["tempfile"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors["tempfile"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];implementors["tempfile"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='tempfile/struct.PersistError.html' title='tempfile::PersistError'>PersistError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
